version: '3'
services: 
  backend:
      build: 
        context: .
        args:         
          AWS_ACCESS_KEY_ID: ...
          AWS_SECRET_KEY: ...
      command: printenv  
      container_name: container-sls-backend
      hostname: container-sls-backend
      image: "img-sls-backend"     
      volumes:
        - .:/usr/src/app
   